import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./style.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (

    <html lang="en">
      {/* <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300..700&family=Poppins:wght@500&display=swap" rel="stylesheet"></link>
      </head> */}
      {/* <head>
        <script src="/feature.js" async/>
      </head> */}
      <head>
        <link rel="stylesheet" href="/style.css"/>
        <script src="/script.js" async/>
      </head>
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
